[tools]
python = "3.12"

[env]
_.python.venv = "venv"

[tasks.dev]
description = "Start the development server"
run = "mkdocs serve --livereload"

[tasks.build]
description = "Build the website"
run = "mkdocs build"

[tasks.preview]
description = "Build & Preview the website"
run = "mkdocs build && python -m http.server -d site"